# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r_packages:
 - devtools

r_github_packages:
 - rqtl/qtl2geno
 - rqtl/qtl2scan

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9

before_install:
  - mkdir -p ~/.R
  - echo "CC=gcc-4.9 -std=gnu99"  >> ~/.R/Makevars
  - echo "CXX=g++-4.9"            >> ~/.R/Makevars
  - echo "CXX1X=g++-4.9"          >> ~/.R/Makevars
  - echo "CXX11=g++-4.9"          >> ~/.R/Makevars
  - echo "CXX1XSTD=-std=c++0x"    >> ~/.R/Makevars
  - echo "CXX11STD=-std=c++0x"    >> ~/.R/Makevars

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: always
